import type { USState } from '@covertree/validation';
import type { WeatherCurrent } from '../weather/weather-provider.js';

export type SortOrder = 'ASC' | 'DESC';

/** A stored property as the rest of the app sees it. The key columns stay in the repository. */
export interface PropertyRecord {
  id: string;
  street: string;
  city: string;
  state: USState;
  zipCode: string;
  lat: number;
  long: number;
  weatherData: WeatherCurrent;
  createdAt: Date;
}

/** Everything the service supplies on create. `id` and `createdAt` are generated by the store. */
export interface NewPropertyData {
  street: string;
  city: string;
  cityKey: string;
  state: USState;
  zipCode: string;
  addressKey: string;
  lat: number;
  long: number;
  weatherData: WeatherCurrent;
}

/** Filter fields that are present constrain the result (AND). Absent fields do not. */
export interface RepositoryFilter {
  cityKey?: string;
  zipCode?: string;
  state?: USState;
}

export interface ListParams {
  filter: RepositoryFilter;
  sortOrder: SortOrder;
  limit: number;
  offset: number;
}

export interface PropertyPage {
  items: PropertyRecord[];
  /** Size of the filtered set, ignoring limit/offset. */
  totalCount: number;
}
